## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
        
   
    obj = bld.create_ns3_program('first', ['core', 'point-to-point', 'internet', 'applications', 'netanim'])
    obj.source = 'first.cc'

    bld.register_ns3_script('first.py', ['internet', 'point-to-point', 'applications' , 'netanim'])


    

